"""
clinical_summary.py
-------------------
Therapist-only, on-demand summary of a session for the licensed clinician.

Produces three parts, all private to the therapist (the client never sees them
through the system):

  1. clinical        — a detailed clinical recap for the therapist.
  2. codes_rationale — a short note on which of the ICD codes that ALREADY
                       surfaced in-session best fit, framed as decision support
                       for billing/coding — never a diagnosis or a determination.
  3. client_recap    — a warm, plain-language recap the therapist MAY choose to
                       hand to the client; contains no codes. The system never
                       delivers it — handover is entirely the therapist's choice.

Each part is generated by its OWN Claude call returning PLAIN TEXT (no JSON).
This is deliberate:

  * No JSON parsing — the previous single combined call returned one JSON object,
    so any truncation or stray prose lost ALL THREE parts silently. Plain text
    per field removes that whole failure class.
  * Independent token budgets — each short field easily fits under max_tokens,
    so the long combined output can no longer be cut off mid-structure.
  * Partial results — if one field's call fails, the others still succeed.

Never raises — each call catches its own failure and returns "" so the caller
(console request or transcript download) always completes. Failures are LOGGED
(no longer silent). The surfaced codes themselves are deterministic (read from
the corpus via the persisted cards), so they are shown even when a narrative is
absent.
"""

import logging

from ai_therapist import _get_claude_client

logger = logging.getLogger(__name__)

__all__ = ["generate", "DISCLAIMER"]

# Opus for the clinical summary: an infrequent, on-demand, quality-sensitive call
# (richer clinical synthesis + tighter grounding than Sonnet). Drop to
# "claude-sonnet-4-6" to trade some quality for lower cost/latency.
SUMMARY_MODEL = "claude-opus-4-8"

# Per-field output ceiling. Each field is only a few paragraphs, so this leaves
# ample headroom; a call that still hits it is logged (see _call) rather than
# silently truncated.
MAX_TOKENS = 6000

DISCLAIMER = (
    "Therapist-only. AI-generated decision support — not a diagnosis and not a "
    "billing or coding determination. The clinician's professional judgment governs."
)

_GROUNDING = (
    "Ground everything strictly in the transcript. Do not invent events, quotes, "
    "or codes. The transcript labels each turn \"Therapist:\", \"Client:\", or \"AI:\". "
    "Output PLAIN TEXT only — no markdown, no headings, no JSON, no preamble, no sign-off."
)

_CLINICAL_SYSTEM = (
    "You are a clinical documentation assistant writing a PRIVATE, therapist-only "
    "clinical recap of a single therapy session. Only the licensed clinician sees it.\n\n"
    "Write a detailed clinical recap: the presenting concern, the key themes, the "
    "emotional arc of the session, any risk or safety signals, and possible next steps "
    "or things to follow up. A few short paragraphs. Clinician-facing tone; clinical "
    "language is fine.\n\n" + _GROUNDING
)

_CODES_SYSTEM = (
    "You are a clinical documentation assistant. A list of reference ICD codes that "
    "ALREADY surfaced during the session is provided.\n\n"
    "Write a brief note on which of THOSE codes (and only those) best fit the material, "
    "and why — a sentence or two each. Frame it explicitly as decision support for "
    "billing/coding consideration — NOT a diagnosis and NOT a billing determination. "
    "Never introduce a code that is not in the provided list. If no codes are provided, "
    "output nothing at all.\n\n" + _GROUNDING
)

_CLIENT_RECAP_SYSTEM = (
    "You are writing a warm, plain-language recap addressed directly to the client "
    "(\"Today we talked about ...\") that the therapist MAY choose to share. It is never "
    "delivered automatically.\n\n"
    "Cover, in a few short paragraphs: what you discussed and why it seems to matter to "
    "them; the main feelings and concerns they shared, reflected back with empathy; any "
    "strengths, insights, or helpful reframes that came up; the concrete next steps, ideas, "
    "or things to try that were agreed or suggested; and a brief encouraging close. Use "
    "supportive, validating, everyday language — NO diagnoses, NO ICD/DSM codes, no clinical "
    "jargon. Be specific to THIS conversation, not generic.\n\n" + _GROUNDING
)


def _call(system_prompt: str, user_content: str, label: str, max_tokens: int = MAX_TOKENS) -> str:
    """Make one plain-text summary call. Returns the text, or "" on failure.

    Never raises. Logs on API failure and on hitting the token ceiling (so a
    truncated field is visible in logs rather than silently cut off).
    """
    try:
        client = _get_claude_client()
        response = client.messages.create(
            model=SUMMARY_MODEL,
            max_tokens=max_tokens,
            system=system_prompt,
            messages=[{"role": "user", "content": user_content}],
        )
    except Exception as exc:
        logger.warning("Clinical summary '%s' call failed (%s); field omitted.", label, exc)
        return ""

    if getattr(response, "stop_reason", None) == "max_tokens":
        logger.warning(
            "Clinical summary '%s' hit the %d-token ceiling — output may be truncated.",
            label, max_tokens,
        )

    # With thinking off, the first content block is the text answer (same shape
    # the copilot call reads). Guard against an empty content list (e.g. refusal).
    try:
        text = response.content[0].text
    except (IndexError, AttributeError):
        return ""
    return (text or "").strip()


def generate(transcript: str, surfaced_codes: list, mode: str = "solo") -> "dict | None":
    """Return {clinical, codes_rationale, client_recap} for the session, or None.

    Each field is produced by its own plain-text Claude call and is "" if that
    call failed. Returns None only when there is no transcript to summarise.
    `surfaced_codes` is a list of dicts with at least "label", "code", "source" —
    the ICD entries that actually appeared in-session. Never raises.
    """
    if not transcript or not transcript.strip():
        return None

    base = f"Session type: {mode}.\n\nTranscript (speaker-labelled):\n{transcript}"

    clinical = _call(
        _CLINICAL_SYSTEM,
        base + "\n\nWrite the clinical recap now.",
        label="clinical",
    )

    if surfaced_codes:
        code_lines = "\n".join(
            f"- {c.get('label', '?')}: {c.get('code', '')} ({c.get('source', '')})"
            for c in surfaced_codes
        )
        codes_rationale = _call(
            _CODES_SYSTEM,
            base
            + "\n\nICD reference codes that surfaced during this session:\n"
            + code_lines
            + "\n\nWrite the codes rationale now.",
            label="codes_rationale",
        )
    else:
        codes_rationale = ""

    client_recap = _call(
        _CLIENT_RECAP_SYSTEM,
        base + "\n\nWrite the client recap now.",
        label="client_recap",
    )

    return {
        "clinical": clinical,
        "codes_rationale": codes_rationale,
        "client_recap": client_recap,
    }
